import { StyleSheet } from 'react-native';

export function createAdminStyles(colors) {
  const isDark = colors.mode === 'dark';

  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
    tabs: {
      flexDirection: 'row',
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    tab: { flex: 1, paddingVertical: 14, alignItems: 'center' },
    tabActive: { borderBottomWidth: 3, borderBottomColor: colors.brand },
    tabText: { color: colors.textSecondary, fontWeight: '600', fontSize: 14 },
    tabTextActive: { color: colors.brand, fontWeight: '700' },
    mainTabText: { color: colors.textSecondary, fontWeight: '600', fontSize: 15 },
    mainTabTextActive: { color: colors.brand, fontWeight: '700' },
    filters: {
      flexDirection: 'row',
      padding: 12,
      gap: 8,
      backgroundColor: colors.card,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    filterChip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.card,
    },
    filterChipActive: { borderColor: colors.brand, backgroundColor: colors.accentSurface },
    filterText: { color: colors.textSecondary, fontWeight: '600', fontSize: 13 },
    filterTextActive: { color: colors.brand, fontWeight: '700', fontSize: 13 },
    heading: { fontSize: 20, fontWeight: '700', marginBottom: 8, color: colors.text },
    sub: { fontSize: 14, color: colors.textSecondary, marginBottom: 16 },
    empty: { textAlign: 'center', color: colors.textMuted, marginTop: 40 },
    card: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
    name: { fontSize: 18, fontWeight: '700', flex: 1, color: colors.text },
    badge: {
      color: '#fff',
      fontSize: 11,
      fontWeight: '700',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      overflow: 'hidden',
      textTransform: 'capitalize',
    },
    meta: { fontSize: 13, color: colors.textSecondary, marginTop: 4 },
    items: { fontSize: 13, color: colors.text, marginTop: 8 },
    row: { flexDirection: 'row', gap: 8, marginTop: 12 },
    switchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginTop: 16,
      marginBottom: 8,
      paddingVertical: 8,
    },
    approveBtn: {
      flex: 1,
      backgroundColor: colors.brandDark,
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    rejectBtn: {
      flex: 1,
      borderWidth: 1,
      borderColor: '#ef4444',
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
      backgroundColor: colors.card,
    },
    btnText: { color: '#fff', fontWeight: '700' },
    rejectText: { color: '#ef4444', fontWeight: '700' },
    smallBtn: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      padding: 10,
      borderRadius: 8,
      alignItems: 'center',
      backgroundColor: colors.card,
    },
    activeBtn: { borderColor: colors.brand, backgroundColor: colors.accentSurface },
    holdBtn: { borderColor: '#f97316', backgroundColor: isDark ? '#422006' : '#fff7ed' },
    disabledBtn: { borderColor: '#9ca3af', backgroundColor: isDark ? colors.cardAlt : '#f3f4f6' },
    smallBtnText: { fontSize: 12, fontWeight: '700', color: colors.text },
    editBtn: {
      marginTop: 12,
      borderWidth: 1,
      borderColor: colors.brand,
      padding: 10,
      borderRadius: 8,
      alignItems: 'center',
      backgroundColor: colors.accentSurface,
    },
    editBtnText: { color: colors.brand, fontWeight: '700', fontSize: 14 },
    deleteBtn: { marginTop: 10, alignItems: 'center', padding: 8 },
    deleteText: { color: '#f87171', fontWeight: '600', fontSize: 13 },
    label: { fontSize: 14, fontWeight: '600', marginBottom: 6, marginTop: 8, color: colors.text },
    input: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      padding: 14,
      marginBottom: 8,
      backgroundColor: colors.inputBg,
      color: colors.text,
      fontSize: 16,
    },
    textArea: { minHeight: 80, textAlignVertical: 'top' },
    previewId: { fontSize: 13, color: colors.brand, fontWeight: '600', marginBottom: 8 },
    chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
    chip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.card,
    },
    chipActive: { borderColor: colors.brand, backgroundColor: colors.accentSurface },
    chipText: { color: colors.textSecondary, fontSize: 13 },
    chipTextActive: { color: colors.brand, fontWeight: '700', fontSize: 13 },
    emptyArea: { color: colors.textMuted, fontSize: 14, marginBottom: 12 },
    secondaryBtn: {
      borderWidth: 1,
      borderColor: colors.brand,
      padding: 12,
      borderRadius: 8,
      alignItems: 'center',
      marginBottom: 16,
      backgroundColor: colors.card,
    },
    secondaryBtnText: { color: colors.brand, fontWeight: '700' },
    modalContainer: { flex: 1, backgroundColor: colors.background },
    modalContent: { padding: 16, paddingBottom: 40 },
    content: { flex: 1 },
  });
}
